name: Run UI tests, generate and publish Allure report on GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests_and_report:
    runs-on: ubuntu-24.04

    env:
      HOME_PAGE: ${{ vars.HOME_PAGE }}
      REGISTRATION_PAGE: ${{ vars.REGISTRATION_PAGE }}
      DRAG_AND_DROP_PAGE: ${{ vars.DRAG_AND_DROP_PAGE }}
      TABS_PAGE: ${{ vars.TABS_PAGE }}
      ALERTS_PAGE: ${{ vars.ALERTS_PAGE }}
      HEADER_PHONE_1: ${{ vars.HEADER_PHONE_1 }}
      HEADER_PHONE_2: ${{ vars.HEADER_PHONE_2 }}
      HEADER_PHONE_3: ${{ vars.HEADER_PHONE_3 }}
      HEADER_SKYPE: ${{ vars.HEADER_SKYPE }}
      HEADER_EMAIL: ${{ vars.HEADER_EMAIL }}
      MENU_ALL_COURSES: ${{ vars.MENU_ALL_COURSES }}
      MENU_VIDEO_TUTORIAL: ${{ vars.MENU_VIDEO_TUTORIAL }}
      MENU_RESOURCES: ${{ vars.MENU_RESOURCES }}
      MENU_CAREERS: ${{ vars.MENU_CAREERS }}
      MENU_LIFETIME_MEMBERSHIP: ${{ vars.MENU_LIFETIME_MEMBERSHIP }}
      MENU_BLOG: ${{ vars.MENU_BLOG }}
      MENU_FORUM: ${{ vars.MENU_FORUM }}
      MENU_MEMBER_LOGIN: ${{ vars.MENU_MEMBER_LOGIN }}
      MENU_ONLINE_TRAINING: ${{ vars.MENU_ONLINE_TRAINING }}
      MENU_CORPORATE_TRAINING: ${{ vars.MENU_CORPORATE_TRAINING }}
      MENU_ALL_COURSES_APPIUM_PYTHON: ${{ vars.MENU_ALL_COURSES_APPIUM_PYTHON }}
      MENU_VIDEO_TUTORIAL_SPRING: ${{ vars.MENU_VIDEO_TUTORIAL_SPRING }}
      LOGIN_PAGE: ${{ vars.LOGIN_PAGE }}
      LOGIN_USERNAME: ${{ vars.LOGIN_USERNAME }}
      LOGIN_PASSWORD: ${{ vars.LOGIN_PASSWORD }}
      BASIC_AUTH_PAGE: ${{ vars.BASIC_AUTH_PAGE }}
      BASIC_AUTH_USERNAME: ${{ vars.BASIC_AUTH_USERNAME }}
      BASIC_AUTH_PASSWORD: ${{ vars.BASIC_AUTH_PASSWORD }}
      AUTH_COOKIES_PAGE: ${{ vars.AUTH_COOKIES_PAGE }}
      AUTH_COOKIES_USERNAME: ${{ vars.AUTH_COOKIES_USERNAME }}
      AUTH_COOKIES_PASSWORD: ${{ vars.AUTH_COOKIES_PASSWORD }}
      ALT_AUTH_COOKIES_PAGE: ${{ vars.ALT_AUTH_COOKIES_PAGE }}
      ALT_AUTH_COOKIES_LOGGED_PAGE: ${{ vars.ALT_AUTH_COOKIES_LOGGED_PAGE }}
      ALT_AUTH_COOKIES_USERNAME: ${{ vars.ALT_AUTH_COOKIES_USERNAME }}
      ALT_AUTH_COOKIES_PASSWORD: ${{ vars.ALT_AUTH_COOKIES_PASSWORD }}

    steps:
      - name: Set up xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Start xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 &

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run UI tests
        run: pytest tests/test_login_page.py --disable-warnings --alluredir=allure-results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: ./allure-results
          allure_history: ./allure-results

      - name: Publish Allure report on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-results
